name: plotly-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - plotly=5.17
  - dash=2.14
  - dash-bootstrap-components=1.5
  - numpy=1.24
  - pandas=2.0
  - scipy=1.11
  - scikit-learn=1.3
  - matplotlib=3.7
  - seaborn=0.12
  - jupyter=1.0
  - jupyterlab=4.0
  - ipykernel=6.25
  - requests=2.31
  - tqdm=4.65
  - pillow=10.0
  - geopandas=0.13
  - folium=0.14
  - pip=23.2
  - pip:
    - kaleido
    - psutil 