name: tf-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tensorflow=2.15
  - numpy=1.24
  - pandas=2.0
  - matplotlib=3.7
  - seaborn=0.12
  - scikit-learn=1.3
  - jupyter=1.0
  - jupyterlab=4.0
  - ipykernel=6.25
  - pillow=10.0
  - requests=2.31
  - tqdm=4.65
  - pip=23.2
  - pip:
    - tensorflow-hub
    - tensorflow-datasets
    - tensorboard
    - keras-tuner 