name: sklearn-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - scikit-learn=1.3
  - numpy=1.24
  - pandas=2.0
  - matplotlib=3.7
  - seaborn=0.12
  - jupyter=1.0
  - jupyterlab=4.0
  - ipykernel=6.25
  - scipy=1.11
  - requests=2.31
  - tqdm=4.65
  - pip=23.2
  - pip:
    - imbalanced-learn
    - yellowbrick
    - mlxtend 