name: python-ai-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - jupyter
  - jupyterlab
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - plotly
  - scikit-learn
  - scipy
  - statsmodels
  - tensorflow
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - opencv-python
  - pillow
  - requests
  - beautifulsoup4
  - nltk
  - spacy
  - gensim
  - wordcloud
  - tqdm
  - joblib
  - psutil
  - memory-profiler
  - line-profiler
  - pytest
  - black
  - flake8
  - mypy
  - pip:
    - streamlit
    - gradio
    - fastapi
    - uvicorn
    - pydantic
    - python-dotenv
    - python-multipart
    - httpx
    - aiofiles
    - jinja2 